de-couple from bash_utils

diff --git a/mylock b/mylock
--- a/mylock
+++ b/mylock
@@ -1,5 +1,9 @@
 #!/usr/bin/env bash
 
+declare -r esc=$'\033'
+declare -r c_red="${esc}[31m"
+declare -r c_reset="${esc}[0m"
+
 declare tmpbg suspend
 # icon="$HOME/.xlock/icon.png"
 tmpbg='/tmp/screen.png'
@@ -8,13 +12,33 @@ finish() {
   [[ -f "$tmpbg" ]] && rm "$tmpbg"
 }
 
-trap finish SIGHUP SIGINT SIGTERM
+err() {
+  printf "${c_red}%s${c_reset}\n" "$*" >&2
+}
+
+has() {
+  local verbose=false
+  if [[ $1 == '-v' ]]; then
+    verbose=true
+    shift
+  fi
+  for c in "$@"; do c="${c%% *}"
+    if ! command -v "$c" &> /dev/null; then
+      [[ "$verbose" == true ]] && err "$c not found"
+      return 1
+    fi
+  done
+}
 
 _suspend() {
   sleep 1
   xset dpms force off
   systemctl suspend
 }
+
+trap finish SIGHUP SIGINT SIGTERM
+
+has -v i3lock maim || die
 
 while :; do
   case "$1" in
diff --git a/mypass b/mypass
--- a/mypass
+++ b/mypass
@@ -1,11 +1,26 @@
 #!/usr/bin/env bash
 
-if [[ -e "${HOME}/.bash_utils" ]]; then
-  source "${HOME}/.bash_utils"
-else
-  printf '\e[31mbash_utils not found\e[0m\n' >&2
-  exit 1
-fi
+declare -r esc=$'\033'
+declare -r c_red="${esc}[31m"
+declare -r c_reset="${esc}[0m"
+
+err() {
+  printf "${c_red}%s${c_reset}\n" "$*" >&2
+}
+
+has() {
+  local verbose=false
+  if [[ $1 == '-v' ]]; then
+    verbose=true
+    shift
+  fi
+  for c in "$@"; do c="${c%% *}"
+    if ! command -v "$c" &> /dev/null; then
+      [[ "$verbose" == true ]] && err "$c not found"
+      return 1
+    fi
+  done
+}
 
 has -v fzf kdbxviewer || die
 
diff --git a/passgen b/passgen
--- a/passgen
+++ b/passgen
@@ -1,18 +1,36 @@
 #!/usr/bin/env bash
 
-if [[ -e "${HOME}/.bash_utils" ]]; then
-  source "${HOME}/.bash_utils"
-else
-  printf '\e[31mbash_utils not found\e[0m\n' >&2
-  exit 1
-fi
-
-set -e
+declare -r esc=$'\033'
+declare -r c_red="${esc}[31m"
+declare -r c_reset="${esc}[0m"
 
 declare maxlength=0
 declare words=0
 declare chars=0
 declare charrange='[a-zA-Z0-9]'
+
+err() {
+  printf "${c_red}%s${c_reset}\n" "$*" >&2
+}
+
+die() {
+  [[ -n "$1" ]] && err "$1"
+  exit 1
+}
+
+has() {
+  local verbose=false
+  if [[ $1 == '-v' ]]; then
+    verbose=true
+    shift
+  fi
+  for c in "$@"; do c="${c%% *}"
+    if ! command -v "$c" &> /dev/null; then
+      [[ "$verbose" == true ]] && err "$c not found"
+      return 1
+    fi
+  done
+}
 
 OPTERR=0
 while getopts "w:c:m:r:" opt; do
