git gud

diff --git a/mypass b/mypass
--- a/mypass
+++ b/mypass
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+declare passlist
+declare password
+
 declare -r esc=$'\033'
 declare -r c_red="${esc}[31m"
 declare -r c_reset="${esc}[0m"
@@ -8,15 +11,20 @@ err() {
   printf "${c_red}%s${c_reset}\n" "$*" >&2
 }
 
+die() {
+  (( $# > 0 )) && err "$*"
+  exit 1
+}
+
 has() {
-  local verbose=false
+  local verbose
   if [[ $1 == '-v' ]]; then
-    verbose=true
+    verbose=1
     shift
   fi
   for c in "$@"; do c="${c%% *}"
     if ! command -v "$c" &> /dev/null; then
-      [[ "$verbose" == true ]] && err "$c not found"
+      (( verbose > 0 )) && err "$c not found"
       return 1
     fi
   done
@@ -24,8 +32,18 @@ has() {
 
 has -v fzf kdbxviewer || die
 
-passlist=$(kdbxviewer -c ~/pass.kdbx)
+OPTERR=0
+while getopts 'i' opt; do
+  case "$opt" in
+    i) kdbxviewer -i ~/pass.kdbx; exit ;;
+  esac
+done
+shift $(( OPTIND - 1 ))
+unset opt OPTARG OPTIND
 
-password=$(fzf --ansi <<< "$passlist")
-
-[[ -n "$password" ]] && xclip <<< "$password"
+passlist=$(kdbxviewer -c ~/pass.kdbx) &&
+  password=$(fzf --inline-info --cycle --ansi <<< "$passlist")
+[[ -n "$password" ]] || exit 1
+password="${password/Generated Password for }"
+read -r password <<< "${password#* }"
+xclip -r <<< "$password"
